One will provide both a topic and a document which represent a party's position on the topic.
Use the document to summarize the party's position solely on the topic and ensure to include the typical party's sentences or slogans used if there are any in this regard. Do not include any other information from the document.
If the document does not contain a position, simply say that the party's position on that matter is according to their general values.

USERINPUT:
{topic}

DOCUMENT:
{document}
